### ISSUE TITLE
Review du formulaire

### ISSUE THREAD

**Issue by ameliedefrance** [Elao/ca-mache-quoi#1]
Côté interface :
- [x] on veut des checkbox pas des radio (`<input type="radio" id="" name="" />` -> `<input type="checkbox" id="" />`)
- [x] il manque un effet au hover sur le bouton submit (foncer la couleur + transition ?)
- [x] il manque un `cursor: pointer` sur les `button`

Général scss : 
- [x] Comme d'habitude, attention aux espaces en trop à la fin de tes fichiers
- [x] Certains de tes styles ont un `_` d'autres pas (`_fonts.scss` etc). Je pense que tu peux les virer partout.

`layout.scss`
- [x] tu as mis un margin sur `form-section` alors que tu as un `container` inutilisé : je pense que c'est lui qui devrait avoir un padding ?

`radio-button.scss`
- [x] `.radio-button {  margin: 0 $radio-button-margin 30px $radio-button-margin }` : tu peux juste écrire `.radio-button {  margin: 0 $radio-button-margin 30px }`
- [x] `img { margin: 7px 17px 7px 30px; }` -> les margin top et bottom devraient être des paddings sur les boutons (parce que qu'est ce qu'il se passe si on a souci à l'affichage des images ? ils sont riquiqui parce que c'est l'image qui donne sa taille aux boutons). Idem pour le margin-left : c'est du padding sur le bouton. On garde uniquement le `margin-right: 17px`

`form.scss`
- [x] `form { margin-right: -40px; }` why ? 🤔
- [x] `.form-group { margin-right: -20px; }` là je comprends, c'est par rapport aux marges sur les `.radio-button` mais pourquoi seulement à droite du coup ? Et du coup tu peux réutiliser la variable qui se trouve dans `radio-button`, comme ça tout bouge d'un coup si on fait une modif.
- [x] Sur la forme : `.form-group` -> `.radio-button-group` car `form-group` pourrait contenir n'importe quel type d'input et là le style qu'on y met est très spécifique et va péter si on met autre chose que nos `radio-button` avec leurs grosses marges

`submit-button.scss`
- [x] `.submit-button` -> `.button` : sur le site on va avoir plusieurs fois des boutons c'est toujours les mêmes, on va pas mettre une classe spécifique par bouton. À terme on aura un `.button` et un `.button--ghost` (transparent) je pense.

`footer.scss`
- [x] attention à l'indentation 4 espaces 

`titles.scss`
- [x] le h1 a une margin-left qui ne devrait pas y être. Cet espace à droite devrait être dans le container

**Comment by sludovicdelys** [comment]
@ameliedefrance le `.button-ghost` c'est celui qui fera office de bouton pour soumettre le formulaire ? 

Actuellement j'ai fait ça dans mon dernier commit : 
-  déplacer le code de `.submit-button` dans un fichier `styles/generic/button.scss`.
-  j'ai renommer la classe en `.button--submit`.

**Comment by ameliedefrance** [comment]
Non le ghost button c'est un bouton transparent ([ici des exemples](https://www.google.com/search?q=ghost+button&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiPhsv21pD3AhVDzYUKHfjoAIQQ_AUoAXoECAEQAw&biw=1919&bih=944&dpr=1)), c'est celui qu'on aura pour le partage du résultat.

En tout on doit avoir seulement deux classes dans `button.scss` -> `button` et `button--ghost`
Celui que tu as appelé `button--submit` ne devrait pas avoir un style particulier lié à sa fonction de bouton submit, c'est juste un banal bouton. Donc inutile d'avoir un _modifier_ dessus.

**Comment by sludovicdelys** [comment]
@ameliedefrance Merci c'est très clair ! 🎉
